export enum EntityStates {
  ACTIVE = 'ACTIVE',
  HISTORICAL = 'HISTORICAL',
  LIQUIDATION = 'LIQUIDATION'
}

export enum DraftStatus {
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  AWAITING_REVIEW = 'AWAITING_REVIEW',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  DRAFT = 'DRAFT',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  PAID = 'PAID',
  WITHDRAWN = 'WITHDRAWN'
}
